### ISSUE TITLE
Suggest, improve project's visibility

### ISSUE THREAD

**Issue by nbehrnd** [marcelmaci/vsteno#1]
I would like to suggest you improve the visibility of your project by either

+ addition of the project's web site address next to the title line (which is optional), or / and
+ the addition of a topics line, allowing a keyword based retrieval within GitHub, too.  It needn't be limited to the programming language(s) deployed.  «stoltze-schrey» isn't around (as by today) but you could create this tag as there already are tags like «gregg»,«kurzschrift», «stenographie», «shorthand», «stenography» (keywords don't start with upper case chars here).  Regardless if there are a few repositories erroneously attributing techniques to «stenography» when indeed relating to «steganography».

**Comment by marcelmaci** [comment]
Hi nbehrnd,
Thx for the suggestion - added website and keywords.
Best regards,
marcelmaci
